package com.glitch.securenotes.data.exceptions.users

class UserNotFoundException: Throwable("User not found")